-- AlterTable
ALTER TABLE `user` ADD COLUMN `firstName` VARCHAR(191) NULL,
    ADD COLUMN `lastName` VARCHAR(191) NULL,
    ADD COLUMN `prefix` VARCHAR(191) NULL,
    ADD COLUMN `suffix` VARCHAR(191) NULL;
