name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci && npm run lint && npm run build

  docker:
    runs-on: ubuntu-latest
    needs: build
#    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v3
        name: Push to Docker Hub
        with:
          push: true
          tags: nehalist/hilde:latest
